### ISSUE TITLE
[Assignment 2] Trash Can

### ISSUE THREAD

**Issue by HQHAN** [kwoolytech/HansCurriculum#2]
Requriement )
- User should be able to add icon by pressing the "Add Icon" Button.
- User should be able to drag an icon by touching and holding and moving it.
- User should be able to remove icon by releasing touch on the trash icon area.
- When icon is being removed , the animation effect (ex. revolving ) should be presented

Purpose )
By performing this assignment, you will be able to learn 
- "how to deal with the touch event" in android 
- "change the view location" as well as "removing/adding View" dynamically
- "Animation part"

Deadline )
Harry should choose :)

**Comment by b01001011** [comment]
Neat description. :) I will try to get it done by this weekend. Thanks!

**Comment by HQHAN** [comment]
@kwoolytech when you put the commit description , please try to add relevant issue No (ex. #2 ) as well.
So your commit history will be shown here in the issue board which makes keeping a track of your patch easier from the issue board.

**Comment by b01001011** [comment]
Great tip! I dig it. Wow.. look at the commit message below. Woot!
