### ISSUE TITLE
[Misc] Get to know how to apply a build variant

### ISSUE THREAD

**Issue by b01001011** [kwoolytech/HansCurriculum#7]
Definition of done:
- Get to know how to build a release APK.
- Get to know how to give name for APK.

**Comment by HQHAN** [comment]
Let's finish this by FW 26. 
I've labeled them with "FW26" milestone

**Comment by HQHAN** [comment]
This looks good to get our feet wet to the build variant world in Android Studio / Gradle build system.

http://blog.robustastudio.com/mobile-development/android/building-multiple-editions-of-android-app-gradle/

**Comment by b01001011** [comment]
I wrote the issue with a misconception on the release and debug build in the Android world. Hans and I agreed that this is not something we really need. Closing for now.
