### ISSUE TITLE
[Misc] Consider using CI tool

### ISSUE THREAD

**Issue by HQHAN** [kwoolytech/HansCurriculum#8]
As a learning opportunity, 
let's try to study CI(continuous integration) tool and apply them into our project.

https://travis-ci.org/getting_started

**Comment by b01001011** [comment]
Hey @HQHAN , Have a look into https://github.com/kwoolytech/Travis-CI-Android-Example 
The travis build succeeded and the result is shown on the README file. Let's have a talk on this sometime durning next week.

**Comment by b01001011** [comment]
I found Travis really interesting but the structure, this repository is employing isn't really fit for Travis. (Travis is designed for one project per repo while this repo contains multiple projects.)  Let's use it for our next project.

**Comment by HQHAN** [comment]
@kwoolytech Thanks for giving it a try for Travis and making a reference repo https://github.com/kwoolytech/Travis-CI-Android-Example. Yes, let's try to use it for our next project !

**Comment by b01001011** [comment]
This is good to close. Closing...
