### ISSUE TITLE
[Assignment_3] Network request

### ISSUE THREAD

**Issue by HQHAN** [kwoolytech/HansCurriculum#9]
Introduction )
Since you have been learning how to populate mockup datas using list view, it is time to take real datas from the cloud (http://openweathermap.org/api ) and populate it using list view.

Requirements )
- App should be able to send the HTTP request 
- App should be able to parse the data from the HTTP response
- App should be able to present the parsed data using ListView widget
  - List Item should contain "Day of week", "Month-Day", "Weather", "Temperature (current, min , max)"
  - ex) Wed, Jun 4 - Cloudy - 35 - 27 / 38
- Network operation should be executed on the Worker Thread
- App should provide the user with the ability to refresh list item

Learning points )
- You can learn how to send the HTTP requests in Android
- You can learn how to read the response data 
- You can learn how to parse the response data in a JSON format
- You can learn how to utilize AsyncTask, typical worker thread in Android.
- You can learn how to add option menu in Android

**Comment by HQHAN** [comment]
@kwoolytech Let's start using a REST API that returns current weather by city name first.
http://openweathermap.org/current

api.openweathermap.org/data/2.5/weather?q={city name}
api.openweathermap.org/data/2.5/weather?q={city name},{country code}

You should get a API key first to be able to use API by signing up
Below is example API that utilize my API key
ex) 
http://api.openweathermap.org/data/2.5/weather?q=Seoul&APPID=82b74b8c1ad71a511604b7054a099de0

**Comment by b01001011** [comment]
This looks awesome! I will dive into it tomorrow. :)

**Comment by b01001011** [comment]
Hey, Hans, Sorry for being silent but I've not been sit on my hand do nothing. :) It was really fun but I have tons of questions. I really look forward to see you on Monday!

**Comment by HQHAN** [comment]
Closing as you've completed this assignment !
